### ISSUE TITLE
Buttercup crashes immediately on Windows

### ISSUE THREAD

**Issue by vikaspotluri123** [buttercup/buttercup-desktop#990]
Congrats on 2.0! 🥳

I just installed 2.0.0, but the app keeps crashing. Here's the log from launching it in powershell:

```
[INF] 20:48:42: Application ready
[INF] 20:48:42: Application session started: 2021-04-11T20:48:42.237Z
[INF] 20:48:42: Logs location: (%localappdata%)\Buttercup-nodejs\Log\buttercup-desktop.log
[INF] 20:48:42: System locale detected: en-US
[INF] 20:48:42: Starting with language: en-US
[INF] 20:48:42: Updated search records for 0 vaults
[INF] 20:48:42: Updated search records for 0 vaults
[ERR] 20:48:42: TypeError: electron_1.systemPreferences.canPromptTouchID is not a function
at <anonymous>              resources/app.asar/build/main/services/biometrics.js:82  return electron_1.systemPreferences.canPromptTouchID();
at next
at                          resources/app.asar/build/main/services/biometrics.js:8   step((generator = generator.apply(thisArg, _arguments || [])).next());
at new Promise
at __awaiter                resources/app.asar/build/main/services/biometrics.js:4   return new (P || (P = Promise))(function (resolve, reject) {
at supportsBiometricUnlock  resources/app.asar/build/main/services/biometrics.js:81  return __awaiter(this, void 0, void 0, function* () {
at                          resources/app.asar/build/main/actions/appMenu.js:34      const biometricsSupported = yield biometrics_1.supportsBiometricUnlock();
at next
at fulfilled                resources/app.asar/build/main/actions/appMenu.js:5       function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reΓÇª
```

The log file mentioned in line 3 does not exist.

It seems to be caused by #988; It looks like [`canPromptTouchID`](https://www.electronjs.org/docs/api/system-preferences#systempreferencescanprompttouchid-macos) is available on macos only

**Comment by Alternus** [comment]
The same error is also occurring on Manjaro Linux when attempting to run the .appimage

**Comment by perry-mitchell** [comment]
Fixed by #994
